Mode: Local

Server:
  Addr: 0.0.0.0
  Port: 8080
  Timeout: 10h

Postgres:
  PostgresHost: localhost
  PostgresPort: 5432
  PostgresUser: postgres
  PostgresPassword: password
  PostgresDbname: test-case