env: "local" #local, prod
storage:
  host: "localhost"                                                                                    
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "test-case"
http_server:
  address: "0.0.0.0:8080"
  timeout: "4s"
  idle_timeout: "60s"